name: Foutatrac
favicon: null
layout_spectrum: 0.53116
typography_spectrum: 0.39783
title: 'Foutatrac, préparer la suite sans attendre la fin'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f0ee'
    - '#106eb6'
    - '#caa49b'
    - '#12110f'
    - '#b9381d'
  brandStrength: 0.5
  lightness: 0.5679577749688178
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
